import {
  Heart,
  Wind,
  Moon,
  Quote,
  Shield,
  TriangleAlert,
  Brain,
  TrendingUp,
  GraduationCap,
  Mail,
  MessageCircle,
  MessageSquare,
  Phone,
  Satellite,
} from 'lucide-react';

export const iconMap = {
  heart: Heart,
  wind: Wind,
  moon: Moon,
  quote: Quote,
  shield: Shield,
  alert: TriangleAlert,
  shieldAlert: Shield,
  brain: Brain,
  chart: TrendingUp,
  graduation: GraduationCap,
  heartShield: Heart,
  mail: Mail,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  phone: Phone,
  satellite: Satellite,
};